### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by v0r73x** [Asteliks/AppleHomeKitADK-ESP32#2]
Hi Asteliks,

I am new in that topic and want to give the esp32 a try to run as homekit device. I already get inspired with the MiaxoiMiaxou IDE example which was easy to understand. Now, since idf i get a little bit lost and have everytime issues how to use it correctly and that ends in errors before i am able to create a bin. The test build is ok and works but all homekit related git versions i tried are messed up with an error.

my worksteps are as following

- I have download the git 
- go into the folder and run this git submodule update recursive command
- then i am unsure - i tried idf.py build -end up with issue CMAKE error in components:224
- cmake error at Cmakelist:2(project) - project command is not scriptable
Callstack
component_get requirements.cmake:96(include)
component_get requirements.cmake:114(--component_get_requirements)

Edit: i tried on Windows (failed) - i tried on Raspberry (no success but ifd was running ok i guess)  on MacOS (error mentioned above)

i am a little bit lost and will be thankfully if you can help here 

best regards from Berlin,

v0r73x

**Comment by Asteliks** [comment]
Hi
For these examples to work you need to slightly modify the esp-idf files. Here you can find the appropriate instructions: https://github.com/espressif/esp-apple-homekit-adk
ones you do that the projects should compile without a problem. If that is not the reason behind your problem could you share with me a more detailed list os steps?
Also feel free to contribute to this project. Here you can find the appropriate [workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962)

Based on this issue I can already see that the documentation needs some improvement

**Comment by Asteliks** [comment]
Closing due to no response
